spring:
  datasource:
    url: jdbc:sqlserver://invoice-contratista.database.windows.net:1433;encrypt=true;trustServerCertificate=false;loginTimeout=30;database=Invoice;
    username: invoice
    password: ale.-112233
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2019Dialect
server:
  port: 9191